server:
  port: 8095

spring:
  application:
    name: nova-mall-pay-web
  profiles:
    include: pay-channel
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:paydb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config


pay:
  channel:
    alipay:
      enabled: true
      gateway: https://openapi.alipay.com/gateway.do
      appId: your-alipay-appid
      privateKey: your-alipay-private-key
      alipayPublicKey: your-alipay-public-key
      notifyUrl: https://your-domain.com/pay/notify/alipay
      returnUrl: https://your-domain.com/pay/return/alipay
    wechat:
      enabled: true
      mchId: your-wechat-mchid
      appId: your-wechat-appid
      apiV3Key: your-wechat-apiv3key
      notifyUrl: https://your-domain.com/pay/notify/wechat
      h5ReturnUrl: https://your-domain.com/pay/return/wechat
    unionpay:
      enabled: true
      merchantId: your-unionpay-merch
      frontUrl: https://your-domain.com/pay/return/unionpay
      backUrl: https://your-domain.com/pay/notify/unionpay
      certPath: classpath:unionpay.pfx
      certPwd: your-cert-pwd
